(function () {
  const CATEGORY_LIST = [
    { id: "youtube_education", label: "YouTube / 教育動画", keywords: ["youtube", "授業", "講義", "解説", "学習", "教育"] },
    { id: "youtube_exam", label: "YouTube / 受験対策", keywords: ["youtube", "受験", "入試", "共通テスト", "試験対策"] },
    { id: "youtube_math", label: "YouTube / 数学", keywords: ["youtube", "数学", "算数", "方程式", "図形"] },
    { id: "youtube_science", label: "YouTube / 理科", keywords: ["youtube", "理科", "物理", "化学", "生物"] },
    { id: "youtube_history", label: "YouTube / 歴史", keywords: ["youtube", "歴史", "世界史", "日本史", "年表"] },
    { id: "youtube_language", label: "YouTube / 語学", keywords: ["youtube", "英語", "語学", "リスニング", "英会話"] },
    { id: "youtube_japanese", label: "YouTube / 国語", keywords: ["youtube", "国語", "現代文", "古文", "漢文"] },
    { id: "youtube_geography", label: "YouTube / 地理", keywords: ["youtube", "地理", "地図", "地形", "気候"] },
    { id: "youtube_civics", label: "YouTube / 公民", keywords: ["youtube", "公民", "政治経済", "倫理", "現代社会"] },
    { id: "youtube_art", label: "YouTube / 美術", keywords: ["youtube", "美術", "art", "デッサン", "イラスト講座"] },
    { id: "youtube_music_study", label: "YouTube / 音楽学習", keywords: ["youtube", "ソルフェージュ", "楽典", "音楽理論"] },
    { id: "youtube_home_economics", label: "YouTube / 家庭科", keywords: ["youtube", "家庭科", "裁縫", "調理実習"] },
    { id: "youtube_physical_education", label: "YouTube / 体育", keywords: ["youtube", "体育", "体操", "スポーツテスト"] },
    { id: "youtube_programming", label: "YouTube / プログラミング", keywords: ["youtube", "programming", "coding", "javascript", "python", "プログラミング"] },
    { id: "youtube_webdev", label: "YouTube / Web制作", keywords: ["youtube", "html", "css", "web制作", "frontend"] },
    { id: "youtube_appdev", label: "YouTube / アプリ開発", keywords: ["youtube", "app development", "ios", "android", "アプリ開発"] },
    { id: "youtube_gamedev", label: "YouTube / ゲーム開発", keywords: ["youtube", "unity", "unreal", "ゲーム開発"] },
    { id: "youtube_robotics", label: "YouTube / ロボット・電子工作", keywords: ["youtube", "arduino", "電子工作", "ロボット"] },
    { id: "youtube_data_science", label: "YouTube / データ分析", keywords: ["youtube", "data science", "データ分析", "統計"] },
    { id: "youtube_ai", label: "YouTube / AI", keywords: ["youtube", "ai", "生成ai", "llm", "機械学習"] },
    { id: "youtube_news", label: "YouTube / ニュース", keywords: ["youtube", "ニュース", "報道", "速報"] },
    { id: "youtube_commentary", label: "YouTube / 解説", keywords: ["youtube", "解説", "考察", "レビュー"] },
    { id: "youtube_documentary", label: "YouTube / ドキュメンタリー", keywords: ["youtube", "documentary", "ドキュメンタリー", "記録映像"] },
    { id: "youtube_interview", label: "YouTube / インタビュー", keywords: ["youtube", "interview", "対談", "インタビュー"] },
    { id: "youtube_podcast", label: "YouTube / ポッドキャスト", keywords: ["youtube", "podcast", "ポッドキャスト"] },
    { id: "youtube_radio", label: "YouTube / ラジオ", keywords: ["youtube", "radio", "ラジオ", "トーク配信"] },
    { id: "youtube_music", label: "YouTube / 音楽", keywords: ["youtube", "mv", "music video", "歌ってみた", "演奏してみた", "音楽"] },
    { id: "youtube_singing", label: "YouTube / 歌ってみた", keywords: ["youtube", "歌ってみた", "cover", "カバー"] },
    { id: "youtube_performance", label: "YouTube / 演奏してみた", keywords: ["youtube", "演奏してみた", "instrumental", "弾いてみた"] },
    { id: "youtube_dance", label: "YouTube / ダンス", keywords: ["youtube", "dance", "踊ってみた", "振付"] },
    { id: "youtube_live", label: "YouTube / ライブ配信", keywords: ["youtube", "live", "配信", "生放送", "stream"] },
    { id: "youtube_archive", label: "YouTube / 配信アーカイブ", keywords: ["youtube", "アーカイブ", "archive", "見逃し配信"] },
    { id: "youtube_short", label: "YouTube / Shorts", keywords: ["youtube", "shorts", "ショート"] },
    { id: "youtube_vlog", label: "YouTube / Vlog", keywords: ["youtube", "vlog", "日常", "密着"] },
    { id: "youtube_family", label: "YouTube / ファミリー", keywords: ["youtube", "family", "家族", "子育てvlog"] },
    { id: "youtube_game", label: "YouTube / ゲーム実況", keywords: ["youtube", "ゲーム実況", "実況", "let's play", "gameplay"] },
    { id: "youtube_walkthrough", label: "YouTube / ゲーム攻略", keywords: ["youtube", "攻略", "ボス攻略", "初心者向け", "立ち回り"] },
    { id: "youtube_speedrun", label: "YouTube / RTA・スピードラン", keywords: ["youtube", "speedrun", "rta", "最速クリア"] },
    { id: "youtube_horror_game", label: "YouTube / ホラー実況", keywords: ["youtube", "ホラーゲーム", "恐怖実況"] },
    { id: "youtube_minecraft", label: "YouTube / Minecraft", keywords: ["youtube", "minecraft", "マイクラ"] },
    { id: "youtube_fortnite", label: "YouTube / Fortnite", keywords: ["youtube", "fortnite", "フォートナイト"] },
    { id: "youtube_splatoon", label: "YouTube / スプラトゥーン", keywords: ["youtube", "splatoon", "スプラトゥーン"] },
    { id: "youtube_pokemon", label: "YouTube / ポケモン", keywords: ["youtube", "pokemon", "ポケモン"] },
    { id: "youtube_variety", label: "YouTube / バラエティ", keywords: ["youtube", "企画", "バラエティ", "ドッキリ", "チャレンジ"] },
    { id: "youtube_comedy", label: "YouTube / お笑い", keywords: ["youtube", "お笑い", "コント", "漫才", "ネタ"] },
    { id: "youtube_storytime", label: "YouTube / 体験談・雑談", keywords: ["youtube", "雑談", "体験談", "語り"] },
    { id: "youtube_reaction", label: "YouTube / リアクション", keywords: ["youtube", "reaction", "リアクション"] },
    { id: "youtube_prank", label: "YouTube / ドッキリ", keywords: ["youtube", "ドッキリ", "prank"] },
    { id: "youtube_anime", label: "YouTube / アニメ", keywords: ["youtube", "アニメ", "anime", "animation"] },
    { id: "youtube_movie", label: "YouTube / 映画・ドラマ", keywords: ["youtube", "映画", "ドラマ", "trailer", "予告"] },
    { id: "youtube_manga", label: "YouTube / 漫画動画", keywords: ["youtube", "漫画動画", "マンガ動画", "ボイスコミック"] },
    { id: "youtube_voice_actor", label: "YouTube / 声優・朗読", keywords: ["youtube", "声優", "朗読", "読み聞かせ"] },
    { id: "youtube_sports", label: "YouTube / スポーツ", keywords: ["youtube", "スポーツ", "試合", "ハイライト", "サッカー", "野球"] },
    { id: "youtube_baseball", label: "YouTube / 野球", keywords: ["youtube", "野球", "baseball", "甲子園"] },
    { id: "youtube_soccer", label: "YouTube / サッカー", keywords: ["youtube", "サッカー", "soccer", "football"] },
    { id: "youtube_basketball", label: "YouTube / バスケットボール", keywords: ["youtube", "バスケ", "basketball", "nba"] },
    { id: "youtube_fishing", label: "YouTube / 釣り", keywords: ["youtube", "釣り", "fishing"] },
    { id: "youtube_outdoor", label: "YouTube / キャンプ・アウトドア", keywords: ["youtube", "camp", "キャンプ", "アウトドア"] },
    { id: "youtube_fitness", label: "YouTube / トレーニング", keywords: ["youtube", "筋トレ", "fitness", "workout", "ストレッチ"] },
    { id: "youtube_cooking", label: "YouTube / 料理", keywords: ["youtube", "料理", "レシピ", "cooking", "食べてみた"] },
    { id: "youtube_food", label: "YouTube / グルメ", keywords: ["youtube", "グルメ", "食レポ", "大食い"] },
    { id: "youtube_travel", label: "YouTube / 旅行", keywords: ["youtube", "旅行", "vlog", "観光", "trip"] },
    { id: "youtube_vehicle", label: "YouTube / 乗り物", keywords: ["youtube", "車", "バイク", "鉄道", "飛行機"] },
    { id: "youtube_train", label: "YouTube / 鉄道", keywords: ["youtube", "鉄道", "train", "電車"] },
    { id: "youtube_car", label: "YouTube / 車", keywords: ["youtube", "車", "car review", "愛車紹介"] },
    { id: "youtube_bike", label: "YouTube / バイク", keywords: ["youtube", "バイク", "motorcycle", "ツーリング"] },
    { id: "youtube_aviation", label: "YouTube / 飛行機", keywords: ["youtube", "飛行機", "aviation", "空港"] },
    { id: "youtube_gadget", label: "YouTube / ガジェット", keywords: ["youtube", "ガジェット", "スマホ", "レビュー", "unboxing"] },
    { id: "youtube_pc", label: "YouTube / PC・自作PC", keywords: ["youtube", "自作pc", "pc build", "ゲーミングpc"] },
    { id: "youtube_camera", label: "YouTube / カメラ", keywords: ["youtube", "camera", "写真機材", "レンズ"] },
    { id: "youtube_beauty", label: "YouTube / 美容・ファッション", keywords: ["youtube", "美容", "メイク", "fashion", "コーデ"] },
    { id: "youtube_craft", label: "YouTube / 工作・DIY", keywords: ["youtube", "diy", "工作", "ものづくり"] },
    { id: "youtube_review", label: "YouTube / 商品レビュー", keywords: ["youtube", "レビュー", "unboxing", "使用感"] },
    { id: "youtube_university", label: "YouTube / 大学・進路", keywords: ["youtube", "大学紹介", "進路", "学部"] },
    { id: "youtube_job", label: "YouTube / 就職・キャリア", keywords: ["youtube", "就活", "キャリア", "面接対策"] },
    { id: "youtube_pet", label: "YouTube / 動物", keywords: ["youtube", "猫", "犬", "ペット", "animal"] },
    { id: "youtube_risk", label: "YouTube / 有害・危険", keywords: ["youtube", "過激", "暴力", "危険", "炎上", "迷惑"] },
    { id: "youtube_other", label: "YouTube / その他", keywords: ["youtube"] },
    { id: "ent_video", label: "エンターテイメント / 総合動画", keywords: ["video", "movie", "youtube", "ニコニコ", "配信", "動画"] },
    { id: "ent_video_short", label: "エンターテイメント / ショート動画", keywords: ["shorts", "short video", "ショート", "リール"] },
    { id: "ent_video_game", label: "エンターテイメント / ゲーム実況動画", keywords: ["gameplay", "実況", "ゲーム実況", "let's play"] },
    { id: "ent_video_music", label: "エンターテイメント / 音楽動画", keywords: ["music video", "mv", "歌ってみた", "演奏してみた"] },
    { id: "ent_video_live_archive", label: "エンターテイメント / 配信アーカイブ", keywords: ["archive stream", "配信アーカイブ", "生配信アーカイブ"] },
    { id: "ent_video_variety", label: "エンターテイメント / バラエティ動画", keywords: ["variety", "おもしろ", "ドッキリ", "企画動画"] },
    { id: "ent_music", label: "エンターテイメント / 音楽", keywords: ["music", "spotify", "sound", "音楽", "歌", "band"] },
    { id: "ent_stream", label: "エンターテイメント / ライブ配信", keywords: ["live", "stream", "twitch", "ライブ", "配信"] },
    { id: "ent_anime", label: "エンターテイメント / アニメ", keywords: ["anime", "アニメ", "animation"] },
    { id: "ent_manga", label: "エンターテイメント / マンガ", keywords: ["manga", "comic", "マンガ", "漫画"] },
    { id: "ent_movie", label: "エンターテイメント / 映画", keywords: ["movie", "cinema", "film", "映画"] },
    { id: "ent_tv", label: "エンターテイメント / テレビ", keywords: ["tv", "テレビ", "broadcast"] },
    { id: "ent_theater", label: "エンターテイメント / 舞台", keywords: ["theater", "舞台", "演劇"] },
    { id: "ent_idol", label: "エンターテイメント / アイドル", keywords: ["idol", "アイドル"] },
    { id: "ent_radio", label: "エンターテイメント / ラジオ", keywords: ["radio", "ラジオ"] },
    { id: "edu_elearning", label: "学習 / eラーニング", keywords: ["elearning", "e-learning", "学習", "講座", "授業"] },
    { id: "edu_video_lesson", label: "学習 / 授業動画", keywords: ["lesson video", "授業動画", "講義動画", "解説動画"] },
    { id: "edu_video_experiment", label: "学習 / 実験動画", keywords: ["experiment", "実験動画", "理科実験"] },
    { id: "edu_video_programming", label: "学習 / プログラミング解説動画", keywords: ["coding tutorial", "programming tutorial", "プログラミング解説", "コード解説"] },
    { id: "edu_video_exam", label: "学習 / 受験対策動画", keywords: ["exam prep", "受験対策動画", "共通テスト", "入試対策"] },
    { id: "edu_research", label: "学習 / 研究", keywords: ["research", "研究", "論文"] },
    { id: "edu_dictionary", label: "学習 / 辞書", keywords: ["dictionary", "辞書", "辞典"] },
    { id: "edu_language", label: "学習 / 語学", keywords: ["language", "英語", "語学", "辞書"] },
    { id: "edu_coding", label: "学習 / プログラミング", keywords: ["code", "coding", "program", "プログラミング", "開発"] },
    { id: "edu_math", label: "学習 / 数学", keywords: ["math", "数学", "算数"] },
    { id: "edu_science", label: "学習 / 理科", keywords: ["science", "理科", "化学", "物理", "生物"] },
    { id: "edu_history", label: "学習 / 歴史", keywords: ["history", "歴史", "世界史", "日本史"] },
    { id: "edu_exam", label: "学習 / 受験", keywords: ["exam", "test", "受験", "試験"] },
    { id: "edu_teacher", label: "学習 / 教師向け", keywords: ["teacher", "教育", "指導", "教材"] },
    { id: "news_general", label: "ニュース / 総合", keywords: ["news", "ニュース", "press"] },
    { id: "news_video", label: "ニュース / 動画ニュース", keywords: ["news video", "動画ニュース", "報道動画"] },
    { id: "news_commentary", label: "ニュース / 解説", keywords: ["commentary", "解説", "特集"] },
    { id: "news_local", label: "ニュース / 地域", keywords: ["local", "地域", "市", "町"] },
    { id: "news_world", label: "ニュース / 国際", keywords: ["world", "international", "国際"] },
    { id: "news_politics", label: "ニュース / 政治", keywords: ["politics", "政治", "政党", "選挙"] },
    { id: "news_economy", label: "ニュース / 経済", keywords: ["economy", "経済", "株", "金融"] },
    { id: "news_weather", label: "ニュース / 天気", keywords: ["weather", "天気", "気象"] },
    { id: "news_disaster", label: "ニュース / 災害", keywords: ["disaster", "災害", "地震", "台風"] },
    { id: "news_sports", label: "ニュース / スポーツ", keywords: ["sports", "スポーツ"] },
    { id: "news_education", label: "ニュース / 教育", keywords: ["education", "教育", "学校"] },
    { id: "news_tech", label: "ニュース / IT", keywords: ["tech", "technology", "IT", "テック"] },
    { id: "sns_microblog", label: "SNS / マイクロブログ", keywords: ["twitter", "x.com", "mastodon", "microblog"] },
    { id: "sns_photo", label: "SNS / 写真", keywords: ["instagram", "photo", "写真"] },
    { id: "sns_video", label: "SNS / 動画SNS", keywords: ["tiktok", "shorts", "リール", "video"] },
    { id: "sns_streamer", label: "SNS / 配信者コミュニティ", keywords: ["streamer", "creator", "配信者", "クリエイター"] },
    { id: "sns_chat", label: "SNS / チャット", keywords: ["chat", "messenger", "ライン", "line"] },
    { id: "sns_community", label: "SNS / コミュニティ", keywords: ["community", "掲示板", "forum", "sns"] },
    { id: "sns_forum", label: "SNS / フォーラム", keywords: ["forum", "bbs", "掲示板"] },
    { id: "sns_blog", label: "SNS / ブログ", keywords: ["blog", "ブログ"] },
    { id: "sns_live", label: "SNS / ライブ配信", keywords: ["live", "stream", "配信"] },
    { id: "sns_voice", label: "SNS / 音声通話", keywords: ["voice", "discord", "通話"] },
    { id: "sns_dating", label: "SNS / マッチング", keywords: ["dating", "match", "出会い"] },
    { id: "game_console", label: "ゲーム / コンソール", keywords: ["switch", "playstation", "xbox", "console"] },
    { id: "game_pc", label: "ゲーム / PC", keywords: ["pc game", "steam", "game"] },
    { id: "game_mobile", label: "ゲーム / モバイル", keywords: ["mobile game", "app game", "スマホ"] },
    { id: "game_browser", label: "ゲーム / ブラウザ", keywords: ["browser game", "flash", "game"] },
    { id: "game_esports", label: "ゲーム / eスポーツ", keywords: ["esports", "eスポーツ"] },
    { id: "game_news", label: "ゲーム / ニュース", keywords: ["game news", "ゲームニュース"] },
    { id: "game_community", label: "ゲーム / コミュニティ", keywords: ["game forum", "guild", "クラン"] },
    { id: "game_mod", label: "ゲーム / MOD", keywords: ["mod", "改造"] },
    { id: "game_stream", label: "ゲーム / 配信", keywords: ["stream", "twitch", "配信"] },
    { id: "game_walkthrough_video", label: "ゲーム / 攻略動画", keywords: ["walkthrough video", "攻略動画", "ボス攻略", "ゲーム解説"] },
    { id: "game_strategy", label: "ゲーム / 攻略", keywords: ["攻略", "walkthrough"] },
    { id: "shop_market", label: "ショッピング / 総合EC", keywords: ["shop", "shopping", "楽天", "amazon"] },
    { id: "shop_auction", label: "ショッピング / オークション", keywords: ["auction", "オークション"] },
    { id: "shop_food", label: "ショッピング / フードデリバリ", keywords: ["delivery", "food", "フード"] },
    { id: "shop_fashion", label: "ショッピング / ファッション", keywords: ["fashion", "apparel", "服"] },
    { id: "shop_electronics", label: "ショッピング / 家電", keywords: ["electronics", "電機", "家電"] },
    { id: "shop_books", label: "ショッピング / 書籍", keywords: ["book", "書籍", "本"] },
    { id: "shop_ticket", label: "ショッピング / チケット", keywords: ["ticket", "チケット"] },
    { id: "shop_coupon", label: "ショッピング / クーポン", keywords: ["coupon", "クーポン"] },
    { id: "shop_subscribe", label: "ショッピング / サブスク", keywords: ["subscription", "サブスク"] },
    { id: "shop_travel", label: "ショッピング / 旅行予約", keywords: ["booking", "travel", "予約"] },
    { id: "life_health", label: "生活/健康 / 健康", keywords: ["health", "健康", "病院"] },
    { id: "life_medical", label: "生活/健康 / 医療", keywords: ["medical", "clinic", "医療", "診療"] },
    { id: "life_fitness", label: "生活/健康 / フィットネス", keywords: ["fitness", "workout", "運動"] },
    { id: "life_diet", label: "生活/健康 / 食事", keywords: ["diet", "料理", "レシピ", "食事"] },
    { id: "life_mental", label: "生活/健康 / メンタル", keywords: ["mental", "カウンセリング", "メンタル"] },
    { id: "life_parenting", label: "生活/健康 / 子育て", keywords: ["parent", "育児", "子育て"] },
    { id: "life_home", label: "生活/健康 / 住まい", keywords: ["home", "house", "不動産"] },
    { id: "life_cooking", label: "生活/健康 / 料理", keywords: ["cook", "recipe", "料理"] },
    { id: "life_finance", label: "生活/健康 / 家計", keywords: ["budget", "家計", "家計簿"] },
    { id: "life_insurance", label: "生活/健康 / 保険", keywords: ["insurance", "保険"] },
    { id: "biz_office", label: "仕事/ビジネス / オフィス", keywords: ["office", "excel", "docs"] },
    { id: "biz_hr", label: "仕事/ビジネス / 人事", keywords: ["hr", "recruit", "採用"] },
    { id: "biz_marketing", label: "仕事/ビジネス / マーケティング", keywords: ["marketing", "広告", "campaign"] },
    { id: "biz_sales", label: "仕事/ビジネス / 営業", keywords: ["sales", "営業"] },
    { id: "biz_crm", label: "仕事/ビジネス / CRM", keywords: ["crm", "customer"] },
    { id: "biz_accounting", label: "仕事/ビジネス / 会計", keywords: ["accounting", "会計", "経理"] },
    { id: "biz_project", label: "仕事/ビジネス / プロジェクト管理", keywords: ["project", "管理", "kanban"] },
    { id: "biz_remote", label: "仕事/ビジネス / リモート", keywords: ["remote", "zoom", "meet", "会議"] },
    { id: "biz_productivity", label: "仕事/ビジネス / 生産性", keywords: ["productivity", "タスク", "todo"] },
    { id: "biz_enterprise", label: "仕事/ビジネス / 企業向け", keywords: ["enterprise", "法人"] },
    { id: "it_cloud", label: "技術/IT / クラウド", keywords: ["cloud", "aws", "azure", "gcp"] },
    { id: "it_storage", label: "技術/IT / ストレージ", keywords: ["drive", "dropbox", "storage", "box.com", "ストレージ"] },
    { id: "it_devtools", label: "技術/IT / 開発ツール", keywords: ["github", "gitlab", "dev", "tool"] },
    { id: "it_security", label: "技術/IT / セキュリティ", keywords: ["security", "sec", "脆弱", "ウイルス"] },
    { id: "it_ai", label: "技術/IT / AI", keywords: ["ai", "ml", "artificial", "機械学習"] },
    { id: "it_ai_video", label: "技術/IT / AI解説動画", keywords: ["ai tutorial", "ai解説", "生成ai", "llm"] },
    { id: "it_data", label: "技術/IT / データ", keywords: ["data", "database", "db", "分析"] },
    { id: "it_hardware", label: "技術/IT / ハード", keywords: ["hardware", "pc", "cpu", "gpu"] },
    { id: "it_network", label: "技術/IT / ネットワーク", keywords: ["network", "router", "wifi"] },
    { id: "it_open", label: "技術/IT / オープンソース", keywords: ["open source", "oss"] },
    { id: "it_hosting", label: "技術/IT / ホスティング", keywords: ["hosting", "server", "vps"] },
    { id: "risk_adult", label: "リスク/有害 / 成人向け", keywords: ["adult", "porn", "アダルト", "18+"] },
    { id: "risk_gambling", label: "リスク/有害 / ギャンブル", keywords: ["casino", "bet", "poker", "ギャンブル", "競馬"] },
    { id: "risk_violence", label: "リスク/有害 / 暴力", keywords: ["violence", "weapon", "暴力", "武器", "銃"] },
    { id: "risk_drugs", label: "リスク/有害 / 薬物", keywords: ["drug", "cannabis", "薬物", "大麻"] },
    { id: "risk_selfharm", label: "リスク/有害 / 自傷", keywords: ["self harm", "自傷", "自殺"] },
    { id: "risk_crime", label: "リスク/有害 / 犯罪", keywords: ["crime", "犯罪", "詐欺"] },
    { id: "risk_hacking", label: "リスク/有害 / ハッキング", keywords: ["hack", "hacking", "不正"] },
    { id: "risk_piracy", label: "リスク/有害 / 海賊版", keywords: ["torrent", "piracy", "海賊版"] },
    { id: "risk_malware", label: "リスク/有害 / マルウェア", keywords: ["malware", "virus", "ウイルス"] },
    { id: "risk_bullying", label: "リスク/有害 / いじめ", keywords: ["bully", "いじめ"] }
  ];

  const CATEGORY_KEYWORDS = {};
  CATEGORY_LIST.forEach((item) => {
    if (item.keywords && item.keywords.length > 0) {
      CATEGORY_KEYWORDS[item.id] = item.keywords;
    }
  });

  const root = typeof window !== "undefined" ? window : self;
  root.MSEFILTER_CATEGORIES = { list: CATEGORY_LIST, keywords: CATEGORY_KEYWORDS };
})();
